name: Detect and Merge RSN Changes

on:
  workflow_run:
    workflows: ["Match RSNs to Discord"]
    types:
      - completed

jobs:
  detect-changes:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Detect RSN changes
        run: |
          python scripts/detect_rsn_changes.py
