name: Full Clan Sync

description: End-to-end workflow for processing new clanrank uploads, matching RSNs to Discord, and detecting RSN changes

on:
  workflow_dispatch:
  push:
    paths:
      - 'uploads/**'

jobs:
  full-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process latest clan rank file
        run: |
          python process_clan_ranks.py

      - name: Match RSNs to Discord
        run: |
          python scripts/match_rsn_to_discord.py

      - name: Detect and merge RSN changes
        run: |
          python scripts/update_matched_members.py

      - name: Git commit and push (if changes)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          # Stash local changes before pulling remote commits
          git stash --include-untracked || true
          git pull origin main --rebase || true
          git stash pop || true

          # Stage and commit any changes
          git add clan_ranks_for_bot.json output/updated_matched_members.json matched_members.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Full sync update"
          git push || echo "Nothing to push or push failed (may be up-to-date)"
