name: Full Clan Sync

on:
  workflow_dispatch:
  push:
    paths:
      - 'uploads/**'

jobs:
  full-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process latest clan rank file
        run: |
          python process_clan_ranks.py

      - name: Match RSNs to Discord
        run: |
          python scripts/match_rsn_to_discord.py

      - name: Detect and merge RSN changes
        shell: bash
        run: |
          if [ ! -s output/latest_rsn_changes.json ]; then
            echo "🟡 No RSN changes to process."
            exit 0
          fi
          python scripts/update_matched_members.py

      - name: Git commit and push (if changes)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          git stash --include-untracked || true
          git pull origin main --rebase || true
          git stash pop || true

          git add clan_ranks_for_bot.json output/*.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Full sync update"
          git push || echo "Nothing to push or push failed (may be up-to-date)"
