name: Match RSNs to Discord

on:
  push:
    paths:
      - 'data/clan_ranks_for_bot.json'
      - 'data/discord_members.csv'
  workflow_dispatch:  # Manual trigger

jobs:
  match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip

      - name: Run RSN matching script
        run: python scripts/match_rsn_to_discord.py

      - name: Commit and push output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.json
          git commit -m "GitHub Actions: Update RSN to Discord match results" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
